# Generated by Django 4.1.5 on 2023-05-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesshop',
            options={'verbose_name': 'Манга', 'verbose_name_plural': 'Манга'},
        ),
        migrations.AddField(
            model_name='articlesshop',
            name='Text',
            field=models.CharField(default='0', max_length=500, verbose_name='Описание манги'),
        ),
    ]
