# Generated by Django 4.1.5 on 2023-05-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangashop', '0003_alter_articlesshop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesshop',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
