# Generated by Django 4.2 on 2023-05-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangashop', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
