# Generated by Django 4.2 on 2023-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangashop', '0006_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesshop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
