# Generated by Django 4.2 on 2023-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangashop', '0007_alter_articlesshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesshop',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
